PS C:\Users\Stephen Galanza> cd desktop
PS C:\Users\Stephen Galanza\desktop> cd galanza_folder
PS C:\Users\Stephen Galanza\desktop\galanza_folder> py --version
Python 3.13.7
PS C:\Users\Stephen Galanza\desktop\galanza_folder> .venv/scripts/activate
(.venv) PS C:\Users\Stephen Galanza\desktop\galanza_folder> py -m django --version
5.2.6
(.venv) PS C:\Users\Stephen Galanza\desktop\galanza_folder> py .\manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 23, 2025 - 10:22:03
Django version 5.2.6, using settings 'galanza_project_folder.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
(.venv) PS C:\Users\Stephen Galanza\desktop\galanza_folder> git remote add origin https://github.com/stephen1524/galanza_repository1_IT373
error: remote origin already exists.